import { useEffect, useMemo, useState } from 'react';
import { AppWindow, Boxes, Eraser, ChevronRight, Clock3, HardDrive, History, KeyRound, LayoutDashboard, Moon, Package, Play, Search, Settings, ShieldCheck, Sun, Trash2, X } from 'lucide-react';
import { useAppStore } from './store';
import { apps, cleanupItems, disks, records, startups } from './mockData';
import { formatBytes, percent } from './format';
import type { Page } from './types';

const nav: {id:Page; label:string; icon: typeof LayoutDashboard}[] = [
  {id:'overview',label:'概览',icon:LayoutDashboard},{id:'cleanup',label:'安全清理',icon:Eraser},{id:'storage',label:'空间分析',icon:HardDrive},
  {id:'apps',label:'应用管理',icon:Package},{id:'startup',label:'启动项',icon:Play},{id:'history',label:'历史记录',icon:History},{id:'settings',label:'设置',icon:Settings}
];

function Dialog({title, body, danger, onClose, onConfirm}:{title:string;body:string;danger?:boolean;onClose:()=>void;onConfirm:()=>void}) {
  return <div className="overlay" role="presentation" onMouseDown={onClose}><div className="dialog" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}>
    <button className="icon-button dialog-close" onClick={onClose} aria-label="关闭"><X size={18}/></button><h2>{title}</h2><p>{body}</p>
    <div className="dialog-actions"><button className="button secondary" onClick={onClose}>取消</button><button className={`button ${danger?'danger':'primary'}`} onClick={onConfirm}>确认执行</button></div>
  </div></div>;
}

function Overview({go}:{go:(p:Page)=>void}) { const d=disks[0], used=d.totalBytes-d.freeBytes; return <section><header className="page-head"><div><p className="eyebrow">系统状态良好</p><h1>下午好，准备好释放空间了吗？</h1><p>上次清理于今天 09:42，释放了 4.82 GB。</p></div><button className="button primary" onClick={()=>go('cleanup')}><Eraser size={18}/>开始扫描</button></header>
  <div className="overview-grid"><div className="disk-panel"><div className="section-title"><span className="drive-icon"><HardDrive/></span><div><h2>{d.name} ({d.mount})</h2><p>{formatBytes(d.freeBytes)} 可用，共 {formatBytes(d.totalBytes)}</p></div><strong>{Math.round(percent(used,d.totalBytes))}%</strong></div><div className="meter large"><span style={{width:`${percent(used,d.totalBytes)}%`}}/></div><div className="legend"><span><i className="dot blue"/>已使用 {formatBytes(used)}</span><span><i className="dot gray"/>可用 {formatBytes(d.freeBytes)}</span></div></div>
  <div className="score"><ShieldCheck/><div><span>清理建议</span><strong>约 14.3 GB</strong><small>5 类文件可以安全检查</small></div></div></div>
  <h2 className="block-title">快捷操作</h2><div className="quick-grid">{[{p:'cleanup' as Page,i:Eraser,t:'安全清理',s:'缓存、临时文件与回收站'},{p:'storage' as Page,i:Search,t:'查找大文件',s:'快速定位占用空间的内容'},{p:'apps' as Page,i:Boxes,t:'管理应用',s:'查看并卸载不再使用的软件'}].map(x=><button className="quick" key={x.t} onClick={()=>go(x.p)}><x.i/><span><strong>{x.t}</strong><small>{x.s}</small></span><ChevronRight/></button>)}</div>
  <h2 className="block-title">最近活动</h2><div className="list">{records.slice(0,2).map(r=><div className="list-row" key={r.id}><span className="row-icon"><Clock3/></span><div className="grow"><strong>{r.title}</strong><small>{r.createdAt} · {r.detail}</small></div><b className="success">+ {formatBytes(r.reclaimedBytes)}</b></div>)}</div></section> }

function Cleanup(){const {scanning,setScanning,progress,setProgress,selected,toggleItem,setSafeDefaults,clearSelection}=useAppStore(); const [confirm,setConfirm]=useState(false); const [done,setDone]=useState(false);
 useEffect(()=>{if(!scanning)return; const t=setInterval(()=>setProgress(Math.min(100,progress+4)),120); if(progress>=100){setScanning(false);setSafeDefaults(cleanupItems);clearInterval(t)}return()=>clearInterval(t)},[scanning,progress,setProgress,setScanning,setSafeDefaults]);
 const selectedSize=cleanupItems.filter(i=>selected.has(i.id)).reduce((a,b)=>a+b.sizeBytes,0); const start=()=>{setDone(false);clearSelection();setProgress(0);setScanning(true)};
 return <section><header className="page-head"><div><h1>安全清理</h1><p>检查系统与应用产生的无用文件，执行前由你确认。</p></div>{!scanning&&<button className="button primary" onClick={start}><Search size={18}/>{progress?'重新扫描':'开始扫描'}</button>}</header>
 {scanning?<div className="scan-state"><div className="scan-ring"><Search/><span>{progress}%</span></div><h2>正在检查可清理内容</h2><p>C:\Users\User\AppData\Local\Temp</p><div className="meter"><span style={{width:`${progress}%`}}/></div><button className="button secondary" onClick={()=>setScanning(false)}>取消扫描</button></div>:<>{done&&<div className="notice success-bg"><ShieldCheck/>清理完成，已释放 {formatBytes(selectedSize)}。</div>}{progress===100&&<><div className="summary-bar"><div><small>已发现</small><strong>{formatBytes(cleanupItems.reduce((a,b)=>a+b.sizeBytes,0))}</strong></div><div><small>已选择</small><strong>{formatBytes(selectedSize)}</strong></div><span>默认仅选择低风险项目</span></div><div className="list cleanup-list">{cleanupItems.map(i=><label className="list-row" key={i.id}><input type="checkbox" checked={selected.has(i.id)} onChange={()=>toggleItem(i.id)}/><div className="grow"><strong>{i.name}<span className={`badge ${i.risk}`}>{i.risk==='low'?'低风险':i.risk==='medium'?'需确认':'高风险'}</span></strong><small>{i.description} · {i.path}</small></div><b>{formatBytes(i.sizeBytes)}</b></label>)}</div><div className="action-bar"><span>将清理 <strong>{formatBytes(selectedSize)}</strong></span><button className="button primary" disabled={!selected.size} onClick={()=>setConfirm(true)}><Trash2 size={18}/>清理所选项</button></div></>}</>}
 {confirm&&<Dialog title="确认清理所选内容？" body={`将处理 ${selected.size} 个类别，预计释放 ${formatBytes(selectedSize)}。缓存文件将永久删除，回收站内容无法恢复。`} danger onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);setDone(true);clearSelection()}}/>}</section>}

function Storage(){return <section><header className="page-head"><div><h1>空间分析</h1><p>按目录、文件类型和大小了解磁盘空间去向。</p></div><button className="button primary"><Search size={18}/>扫描磁盘</button></header><div className="storage-layout"><div><h2 className="block-title">存储分布</h2><div className="storage-bar"><span style={{width:'34%',background:'#3578e5'}}/><span style={{width:'22%',background:'#17a673'}}/><span style={{width:'17%',background:'#e6a23c'}}/><span style={{width:'12%',background:'#8a63d2'}}/></div><div className="category-grid">{[['应用和游戏','112.4 GB','#3578e5'],['图片与视频','72.1 GB','#17a673'],['系统和保留','55.9 GB','#e6a23c'],['其他','39.5 GB','#8a63d2']].map(x=><div><i style={{background:x[2]}}/><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><h2 className="block-title">最大的文件夹</h2><div className="list">{[['Users','168.2 GB'],['Program Files','82.4 GB'],['Windows','51.7 GB'],['ProgramData','18.6 GB']].map((x,i)=><div className="list-row"><span className="rank">{i+1}</span><div className="grow"><strong>{x[0]}</strong><small>C:\{x[0]}</small></div><b>{x[1]}</b><ChevronRight size={17}/></div>)}</div></div><aside className="side-tool"><h2>智能查找</h2><button><Search/><span><strong>大文件</strong><small>超过 1 GB 的文件</small></span><ChevronRight/></button><button><Boxes/><span><strong>重复文件</strong><small>按内容哈希精确比较</small></span><ChevronRight/></button><p>分析结果仅供查看，不会自动删除任何文件。</p></aside></div></section>}

function Apps(){const [target,setTarget]=useState<string|null>(null);return <section><header className="page-head"><div><h1>应用管理</h1><p>查看已安装应用及其空间占用。</p></div><div className="searchbox"><Search/><input aria-label="搜索应用" placeholder="搜索应用"/></div></header><div className="table"><div className="table-head"><span>应用</span><span>安装日期</span><span>大小</span><span/></div>{apps.map(a=><div className="table-row"><span className="app-name"><span className="app-icon">{a.name[0]}</span><span><strong>{a.name}</strong><small>{a.publisher} · {a.version}</small></span></span><span>{a.installedAt}</span><span>{formatBytes(a.sizeBytes)}</span><button className="button secondary small" onClick={()=>setTarget(a.id)}>卸载</button></div>)}</div>{target&&<Dialog title={`卸载 ${apps.find(a=>a.id===target)?.name}？`} body="将启动该应用自己的卸载程序。清盘不会直接删除程序目录。" danger onClose={()=>setTarget(null)} onConfirm={()=>setTarget(null)}/>}</section>}

function Startup(){const [rows,setRows]=useState(startups); const [target,setTarget]=useState<string|null>(null);const toggle=(id:string)=>setRows(r=>r.map(x=>x.id===id?{...x,enabled:!x.enabled}:x));return <section><header className="page-head"><div><h1>启动项</h1><p>减少不必要的开机自启动，让系统更快就绪。</p></div></header><div className="notice"><ShieldCheck/>系统安全相关启动项应保持开启。</div><div className="table startup-table"><div className="table-head"><span>名称</span><span>影响</span><span>范围</span><span>状态</span></div>{rows.map(x=><div className="table-row"><span className="app-name"><span className="row-icon"><AppWindow/></span><span><strong>{x.name}</strong><small>{x.publisher}</small></span></span><span><b className={`impact ${x.impact}`}>{x.impact}</b></span><span>{x.scope}</span><button role="switch" aria-checked={x.enabled} className={`switch ${x.enabled?'on':''}`} onClick={()=>setTarget(x.id)}><span/></button></div>)}</div>{target&&<Dialog title={`${rows.find(x=>x.id===target)?.enabled?'禁用':'启用'}此启动项？`} body="更改会在下次登录 Windows 时生效，你可以随时恢复。" onClose={()=>setTarget(null)} onConfirm={()=>{toggle(target);setTarget(null)}}/>}</section>}

function HistoryPage(){return <section><header className="page-head"><div><h1>历史记录</h1><p>所有清理与系统修改都会保留本地记录。</p></div></header><div className="list history-list">{records.map(r=><div className="list-row"><span className="row-icon"><History/></span><div className="grow"><strong>{r.title}<span className={`badge ${r.status==='success'?'low':'medium'}`}>{r.status==='success'?'已完成':'部分完成'}</span></strong><small>{r.createdAt} · {r.detail}</small></div><b>{formatBytes(r.reclaimedBytes)}</b></div>)}</div></section>}
function SettingsPage(){const {theme,setTheme}=useAppStore();return <section><header className="page-head"><div><h1>设置</h1><p>调整外观、安全和扫描偏好。</p></div></header><div className="settings-group"><h2>外观</h2><div className="setting-row"><span><strong>应用主题</strong><small>选择清盘的显示方式</small></span><div className="segments">{(['system','light','dark'] as const).map((x,i)=><button className={theme===x?'active':''} onClick={()=>setTheme(x)}>{[<AppWindow/>,<Sun/>,<Moon/>][i]}{['跟随系统','浅色','深色'][i]}</button>)}</div></div></div><div className="settings-group"><h2>安全</h2><div className="setting-row"><span><strong>删除前始终确认</strong><small>危险操作无法关闭确认步骤</small></span><span className="locked"><KeyRound/>已启用</span></div><div className="setting-row"><span><strong>匿名使用数据</strong><small>清盘不会收集或上传任何使用数据</small></span><span>关闭</span></div></div></section>}

export default function App(){const {page,setPage,theme}=useAppStore(); useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]); return <div className="app-shell"><aside className="sidebar"><div className="brand"><span><Eraser/></span><strong>清盘</strong><small>空间管理</small></div><nav>{nav.slice(0,5).map(x=><button className={page===x.id?'active':''} onClick={()=>setPage(x.id)}><x.icon/>{x.label}</button>)}</nav><nav className="nav-bottom">{nav.slice(5).map(x=><button className={page===x.id?'active':''} onClick={()=>setPage(x.id)}><x.icon/>{x.label}</button>)}</nav><div className="license"><ShieldCheck/><span><strong>专业版已激活</strong><small>设备许可有效</small></span></div></aside><main>{page==='overview'&&<Overview go={setPage}/>} {page==='cleanup'&&<Cleanup/>}{page==='storage'&&<Storage/>}{page==='apps'&&<Apps/>}{page==='startup'&&<Startup/>}{page==='history'&&<HistoryPage/>}{page==='settings'&&<SettingsPage/>}</main></div>}
